### ISSUE TITLE
ExactReach stuck in translate

### ISSUE THREAD

**Issue by castrong** [sisl/NeuralVerification.jl#114]
ExactReach seems to get stuck in the function call:

`translate(v::Vector, V::AbstractPolytope) = tohrep(VPolytope([x+v for x in vertices_list(V)]))`.

vertices_list(V) has a length of 16 so I wouldn't have expected this to be too costly of an operation. Perhaps I'm misunderstanding it though and it will take a very long time to perform. 

Code to reproduce is:

```
network = NeuralVerification.read_nnet("./test/test_sets/random/medium/networks/rand_[4,8,4]_1.nnet")
input_set = NeuralVerification.HPolytope{Float64}([NeuralVerification.HalfSpace{Float64}([1.0, 0.0, 0.0, 0.0], 0.3845579517032085), NeuralVerification.HalfSpace{Float64}([0.0, 1.0, 0.0, 0.0], 0.8331193586918577), NeuralVerification.HalfSpace{Float64}([0.0, 0.0, 1.0, 0.0], 0.6607352829885846), NeuralVerification.HalfSpace{Float64}([0.0, 0.0, 0.0, 1.0], 0.270232549769154), NeuralVerification.HalfSpace{Float64}([-1.0, 0.0, 0.0, 0.0], 0.022984248429274823), NeuralVerification.HalfSpace{Float64}([0.0, -1.0, 0.0, 0.0], 1.061033037362016), NeuralVerification.HalfSpace{Float64}([0.0, 0.0, -1.0, 0.0], 0.734914583454296), NeuralVerification.HalfSpace{Float64}([0.0, 0.0, 0.0, -1.0], 0.7494557834041424)])
output_set = NeuralVerification.HPolytope{Float64}(NeuralVerification.HalfSpace{Float64}[NeuralVerification.HalfSpace{Float64}([1.0, 0.0, 0.0, 0.0], 0.47919249361761995), HalfSpace{Float64}([0.0, 1.0, 0.0, 0.0], 0.21600299802246092), HalfSpace{Float64}([0.0, 0.0, 1.0, 0.0], 0.13753126667274596), HalfSpace{Float64}([0.0, 0.0, 0.0, 1.0], 0.536256411404834), HalfSpace{Float64}([-1.0, 0.0, 0.0, 0.0], 0.05623084997936845), HalfSpace{Float64}([0.0, -1.0, 0.0, 0.0], -0.02937453504189702), HalfSpace{Float64}([0.0, 0.0, -1.0, 0.0], 0.7988290732045045), HalfSpace{Float64}([0.0, 0.0, 0.0, -1.0], 1.1397183250614469)])
problem = NeuralVerification.Problem(network, input_set, output_set)

# Exact Reach issue
println(NeuralVerification.solve(NeuralVerification.ExactReach(), problem))

```

With network:

//Neural Network File Format by Kyle Julian, Stanford 2016.
2, 4, 4, 8,
4, 8, 4,
This line extraneous
-6.55e4,-6.55e4,-6.55e4,-6.55e4,
6.55e4,6.55e4,6.55e4,6.55e4,
0.0,0.0,0.0,0.0,0.0,
1.0,1.0,1.0,1.0,1.0,
-0.23004744778871178, 0.9210992236909084, -0.030635894568796118, -0.34332947427825244,
0.8978626764268087, 0.8309944551520903, -0.014461773871067951, -0.6884545083395874,
-0.9571306885211475, -0.4651249798060011, 0.8927464935383509, 0.23779053079463175,
0.2796571501428917, -0.4114885625241218, -0.05410680573253712, 0.6629014622254301,
-0.8632374852957523, 0.5957105726470227, 0.5747178822778407, 0.1353980115540212,
0.43882314695613855, -0.002452754445515737, 0.6443817883537535, -0.23630991424169778,
0.03346675961844259, 0.7115606398658421, 0.4798026539014697, -0.47832685658716123,
-0.5636833238093555, 0.04214094639926591, 0.7385695072981133, 0.6656665947649203,
0.6162281231994049,
-0.2842576636476495,
0.17361456246025053,
-0.8145690340743399,
0.9609853991020589,
0.7041393195522954,
0.38275285236140943,
-0.7922435452981706,
0.5566377731659151, -0.22097068945875353, 0.8681055231723533, 0.6648609539585149, 0.8963076897599609, -0.9407432187803808, 0.5519973844436779, 0.9539313268084384,
0.672011854126858, 0.7873646431266152, -0.48281530198422296, 0.056392080910015796, -0.7497530830241459, 0.22864777607158127, 0.05450773274033782, -0.7405932810079814,
-0.9107076528782465, 0.33876887402212397, 0.18209738189045765, 0.17489511201142527, -0.4812871934319878, -0.8244163696913085, 0.425612874065187, -0.889371405676664,
-0.2995076129559373, -0.44135435764626374, 0.15240142012015, 0.17114545464001596, 0.7469225136257442, -0.571483866728244, -0.8498590494961284, -0.4970584819809667,
0.9493071313547716,
-0.4000560612181365,
-0.9141989352816746,
0.2665395852249475,

**Comment by mforets** [comment]
> vertices_list(V) has a length of 16 so I wouldn't have expected this to be too costly of an operation

It is not the translation that is costly, it is the conversion to the dual representation:

```julia
julia> using LazySets

julia> x = rand(VPolytope, dim=10);

julia> d = rand(10);

julia> @time translate(x, d);
  0.000008 seconds (50 allocations: 8.000 KiB)

julia> x = convert(HPolytope, rand(Hyperrectangle, dim=10));

julia> @time translate(x, d);
  0.000021 seconds (83 allocations: 7.625 KiB)
```

**Comment by tomerarnon** [comment]
`LazySets`′ `translate` doesn't suffer from this problem. I believe it wasn't yet implemented when we first needed it, but the obvious fix for this now is to just eliminate our version.

**Comment by mforets** [comment]
>  I believe it wasn't yet implemented when we first needed it

yes, i think so. in fact, all the features from [this thread](https://github.com/sisl/NeuralVerification.jl/issues/46#issuecomment-467517478) were implemented some time ago.
