### ISSUE TITLE
forward_partition in reachability.jl gives incorrect output for large n.

### ISSUE THREAD

**Issue by castrong** [sisl/NeuralVerification.jl#129]
In reachability.jl, forward_partition finds the dimension of the layer then iterates through all activation states of that layer. This will be 2^n states. When n is large, say n = 200,  2^n will return 0. This makes it so that forward_partition returns an empty list in this case. This leads to issues with Ai2 and likely other reachability based solvers as well. With large enough n this function should probably throw a warning or an error.

**Comment by tomerarnon** [comment]
True. If we preallocated the result vector we would throw a `MemoryAllocationError`, which is probably the right thing to do for too high `n`. However, we `push!` dynamically to the result to avoid storing many empty sets even in cases with a reasonable number of dimensions. We can use a `sizehint!` at the start,  which will throw an `InexactError` (not particularly informative though)
```
julia> sizehint!(x, big(2)^200)
ERROR: InexactError: UInt64(1606938044258990275541962092341162602522202993782792835301376)
```
Note the `big(2)`, which is the main fix here (not letting integer rollover happen). Just adding the promotion to `big` will technically solve the problem, but will lead inexperienced users to hang forever in the for-loop. I'd rather have a way of exiting with an error if they're making that mistake.

**Comment by castrong** [comment]
Do we want a maximum size of 2^n? Could we set some @assert when starting to solve a problem that requires using this forward_partition which asserts that n is less than some constant? Say 20 or 30? This could go in the solve method. Alternatively we could add @assert n < max_n with an appropriate message to the start of forward_partition.

**Comment by tomerarnon** [comment]
We could do something like that. We'd be arbitrarily limiting the dimensionality of the problem (if anyone ever wants to solve it on a super computer they'd have to go in and edit that. We could set a limiter that can be overridden...

**Comment by castrong** [comment]
Yeah I like that idea so that no one is restricted if they don't want to be. We could store it in a similar way to the global tolerance with a setter function for those who wish to modify it and the assert in reachability.jl can direct people to this setter function?

**Comment by tomerarnon** [comment]
Actually, in that case, how about we just issue a warning for some hard coded `n > n_max` and let the user decide if what they're doing makes sense?
