### ISSUE TITLE
MaxSens resolution not working

### ISSUE THREAD

**Issue by SebastianGuadalupe** [sisl/NeuralVerification.jl#140]
When debugging for the error, it seems to me that is in the function `partition(input::Hyperrectangle, Δ)`, printing the set before and after, the set is empty after the function is used. When using `solve(MaxSens(resolution = 0), problem_mnist)`, the algorithm works fine, so `Δ == 0 && return [input]` it's doing its job and can be used as a workaround.

**Comment by tomerarnon** [comment]
ARGH! I was sure length(CI) would return a BigInt (or throw an error) if the size was too big. Instead, this is again an issue with integer overflow. Trivial to fix, luckily.
