### ISSUE TITLE
NSVerify and Certify disagreement - likely Certify unsoundness

### ISSUE THREAD

**Issue by castrong** [sisl/NeuralVerification.jl#148]
**With code:**

```
# Setup problem
network = NeuralVerification.read_nnet("./examples/networks/issue_net.nnet")
input_set = LazySets.Hyperrectangle([-0.45152502013180396, 0.41490885993639925, 0.2782117602091192, 0.3791775198374763, 0.0889429904093384], [0.23933793427605798, 0.21323138370049222, 0.8097787665919143, 0.29980568419469433, 0.2538086032018707])
output_set = LazySets.HalfSpace([0.3108219215140573], 0.06753661906010833)
problem = NeuralVerification.Problem(network, input_set, output_set)

# Solve on NSVerify and Certify
ns_status = NeuralVerification.solve(NeuralVerification.NSVerify(), problem).status
certify_status =  NeuralVerification.solve(NeuralVerification.Certify(), problem).status
println("NSVerify status: ", ns_status)
println("Certify status: ", certify_status)
```

**And Network: **
//Neural Network File Format by Kyle Julian, Stanford 2016.
2, 1, 1, 8,
1, 8, 1,
This line extraneous
-6.55e4,
6.55e4,
0.0,0.0,
1.0,1.0,
0.2872676790717188, 0.2384668744592906, -0.44125516640242823, 0.5465712420076443, -0.24896079757531542,
0.5792632143810761, 0.2659379850546726, 0.2601311416768719, -0.09235576858895866, -0.11774237539899213,
0.14693833502012943, 0.6983719636533263, -0.601408042242312, -0.42743595522241495, 0.18005520856745783,
0.5611334682654365, 0.17037821240919948, 0.4253753284109085, -0.061366248421686365, -0.2209641334251291,
0.13658909983845025, -0.04408264830025432, 0.5619157427005494, 0.1825227545231236, 0.07550581253069577,
-0.9400984464247242, 0.1335917835270557, 0.6531033799717818, 0.720156430988613, -0.9710374998633284,
0.28114652109517735, -0.525770001666003, 0.01815906718941207, -0.6529967296312749, 0.9093352856119874,
0.08893278839669216, 0.42638435381082607, 0.13813630009257016, -0.07893949599957129, 0.15451868717464734,
-0.978260090997745,
0.6222459141130194,
0.6762121978305133,
0.2637708085521182,
-0.8253694148584749,
-0.670679805871389,
-0.8557945099771365,
-0.345794354157015,
0.19664947133375055, -0.06933392443359221, -0.565351163560257, 0.7368358787425437, -0.3610292123421357, 0.7473484226738498, -0.24110358006565047, 0.3955637116023536,
-0.6881105607698719,

**We get the following output: **

NSVerify status: violated
Certify status: holds

This means that either NSVerify is acting incompletely or Certify is acting unsoundly. Certify also disagrees with Planet, Reluplex, and MIPVerify so it's likely that Certify is the issue.

**Comment by AvrahamRaviv** [comment]
Nsverify should return a counterexample, you can check if thia is real counterexample. If yes, you can be surely that Certify ia the isuue
