### ISSUE TITLE
How to understand this line ?

### ISSUE THREAD

**Issue by LLwyct** [sisl/NeuralVerification.jl#191]
https://github.com/sisl/NeuralVerification.jl/blob/457a556197a9cf34c04e8d516de21f3e3641c2f6/src/reachability/reluVal.jl#L125

if UPPER equation's upper bound > 0, and UPPER equation's lower bound < 0.

and the `output_Up` is a two dim matrix.

Why just the last element in output_Up[j] need to be covered by UPPER equation's upper bound[j]?

```
...
0 0 0 0 ... 0 0 6.5
...
```

i have learned this code one week. if i don't set `output_Up[j]` to zero, the result is ok in verify acasxu, but there will be mistake in verifying mnist. e.g. lower bounds will greater than upper bounds.

if i set `output_Up[j]` to zero, all result is wrong. so i think, in this code, first set `output_Up[j]` to zero, and set the last element to a strang value, maybe i ignore this opreation. but i can't understand this line code.

so , can anyone help me ？ pls

**Comment by tomerarnon** [comment]
The comment above that block attempts to explain it:
https://github.com/sisl/NeuralVerification.jl/blob/457a556197a9cf34c04e8d516de21f3e3641c2f6/src/reachability/reluVal.jl#L117-L126

Setting each column to 0 turns the set representing the upper bound into a point (these columns are the generators of the set). The last column represents the "bias" term, i.e. where the center of the set is located (following the convention of the original ReluVal paper). We set the new center of the *upper bound set* to be the upper-most point of the previous upper bound estimate we had (aka the upper-bound of the upper-bound). This isn't the only correct way to deal with the upper bound in such a case, but it's very reasonable and it's the way the authors went with. 

I'm not sure I understand which changes you made and what effect they had, but in general I can say that setting the new upper bound to 0 would be wrong (because in this branch of the code we have the upper bound strictly greater than 0).

**Comment by LLwyct** [comment]
@tomerarnon 
very very very Thank you for your reply！

I am trying to use python to implement reluval. And I referenced the code in Venus.

I distinguish Equation and bounds. And `Equation.dot(input) is bounds`. And Equation is composed of matrix and offset. The offset here is the layer-by-layer accumulation of bias, and so is the matrix. so `Equation.dot(input) + offset is bounds`。

this is my code

```py
# UpEquation's upper bounds
# inUPEq.dot(input)'s upper
UPEqUpper = inUPEq.computeMaxBoundsValue(inputLayer)
# UpEquation's lower bounds
UPEqLower = inUPEq.computeMinBoundsValue(inputLayer)

# LowEquation's upper bounds
LOWEqUpper = inLOWEq.computeMaxBoundsValue(inputLayer)
# LowEquation's lower bounds
LOWEqLower = inLOWEq.computeMinBoundsValue(inputLayer)

# self.size means size of this ReluLayer, i means each node in this Layer
for i in range(self.size):
    # if upper bounds of up Equation < 0, upperbounds and lowerbounds can't go through ReluLayer, so set this row all to zero
    # if row i of matrix all set zero, then the bounds[i] = matrix[i].dot(input) also is zero
    if UPEqUpper[i] <= 0:
        newUpMatrix[i,:] = 0
        newUpOffset[i] = 0
        newLowMatrix[i, :] = 0
        newLowOffset[i] = 0
    elif LOWEqLower[i] >= 0:
        # do nothing, else maintain original Matrix
        continue
    else:
        # set Low Equation to zero, because it can't go through ReluLayer, and don't care the upperbounds of LowEquation may >0 in fact
        newLowMatrix[i,:] = 0
        newLowOffset[i] = 0
        # Special processing upper Equation, if lower bounds of Upper Equation < 0
        if UPEqLower[i] < 0:
            newUpMatrix[i,:] = 0
            newUpOffset[i] = ?
```

Maybe  i think it will be this，If i understand correctly

```
if UPEqLower[i] < 0:
        newUpMatrix[i,:] = 0
        newUpOffset[i] = UPEqUpper[i]
```
---

In your first line of reply 

>Setting each column to 0 turns ...

maybe Setting each row to zero ?

I did not find the concept related to the word "center" in the original paper. But I think your reply inspired me because I am not very clear about the mathematical principles in the paper. So I am very interested in the concept of center.

But I am at home these few days. When I go to school, I will study your reply carefully. Very Thank you again.

**Comment by tomerarnon** [comment]
>maybe Setting each row to zero ?

Yes, that was a mistake! Each *row* corresponds to a generator.

>I did not find the concept related to the word "center" in the original paper.

By "center" I meant the same as the bias; i.e. it is the offset.

>   newUpOffset[i] = UPEqUpper[i]

This looks right to me (assuming I understand `UpEqUpper`)! It should be equivalent to the furthest distance in the set in the direction of the ith basis vector. Or in other words, it is the upper bound on that node's upper bound. It seems natural that this is what `computeMaxBoundsValue` is returning.

**Comment by LLwyct** [comment]
@tomerarnon 
thank you ！I have finished my code, , i am testing it and seem no problem now.
