### ISSUE TITLE
PicoSAT breaking build/test

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#22]
I forgot that we each fixed PicoSAT privately (to get it to work with 1.0) ~2 months ago. I left an issue on the repo a while back but it hasn't had any activity in 6 months.

This fork does the same thing we did: https://github.com/kopptr/PicoSAT.jl, but I'm not sure how to require a particular fork in the Project/Manifest, so still reading up on it.

@mykelk have you encountered a situation like this before?

**Comment by mykelk** [comment]
@rejuvyesh or @MaximeBouton can probably tell you the best way to do it. In the mean time, you can add it manually in the build script in deps/build.jl. See https://julialang.github.io/Pkg.jl/v1/creating-packages/.

**Comment by tomerarnon** [comment]
Tried something 🤷‍♂️

**Comment by tomerarnon** [comment]
This issue is fixed. 
Build is still failing on linux though
