### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#23]
The error maybe has to do with different filesystems?

[error](https://travis-ci.org/sisl/NeuralVerification.jl/jobs/476173583):
```julia
ERROR: LoadError: LoadError: could not open file  
/home/travis/build/sisl/NeuralVerification.jl/src/adversarial/FastLin.jl
```

**Comment by mykelk** [comment]
It's due to the fact that linux is strict about the file name capitalization. Your error has FastLin.jl in caps, but the actual file starts lowercase.
