### ISSUE TITLE
Max pooling

### ISSUE THREAD

**Issue by mykelk** [sisl/NeuralVerification.jl#28]
We have `Max` but not max-pooling activation. This should be easy to add. Make sure we test it. We'd want to add it to the paper as well.

**Comment by clazarus** [comment]
According to our discussion we concluded that directly supporting Maxpooling would require modifying the implementations of the algorithms significantly. Accordingly, an explanation of how to represent a Maxpooling operation using a combination of ReLU's will be added to the documentation.
