### ISSUE TITLE
Reluplex should support HPolytope input/output

### ISSUE THREAD

**Issue by clazarus** [sisl/NeuralVerification.jl#30]
HPolytope's are more expressive than Hyperrectangles as they are able to represent relationships among input and among output variables beyond hypercubes that are parallel to the canonical axes (such as x_1 > x_2) . There is no algorithmic reason why Reluplex couldn't support them so this feature will be incorporated.

**Comment by clazarus** [comment]
In a similar fashion to Planet (discussed in https://github.com/sisl/NeuralVerification.jl/issues/31), Reluplex calls get_bounds():
https://github.com/sisl/NeuralVerification.jl/blob/fd13740377b0eedd6f8a433aea78800c2395dc8e/src/satisfiability/reluplex.jl#L77

which currently only supports instances of Problem with a Hyperrectangle Input set. Reluplex could easily support HPolytope Input sets but computing and propagating the bounds would not be possible. HPolytope's can represent more complex Input sets than Hyperrectangles and are thus preferable but propagating the bounds is expected to speed-up the solution of the LP subproblems.

For now, Reluplex will continue to only support Hyperrectangle Input sets until this matter is further discussed.

**Comment by tomerarnon** [comment]
closed by #52
