### ISSUE TITLE
SAT/UNSAT to holds/violated

### ISSUE THREAD

**Issue by mykelk** [sisl/NeuralVerification.jl#38]
It was suggested by @guykatzz to change `:SAT` and `:UNSAT` to `:holds` and `:violated` to reduce confusion by others in the FM community.

**Comment by clazarus** [comment]
👍 I agree that it can be confusing and support the motion to change it. In fact, I was confused with this when I first ported Reluplex to Julia and that confusion was the origin of the bug that I just fixed last week. I had to do a triple negation in my mind to figure it out  😆. I will follow this thread and update the return types once the wording is settled.

**Comment by changliuliu** [comment]
I prefer ```:unsatisfied``` and ```:satisfied```.

**Comment by clazarus** [comment]
Ok, I will add this to my to-do's and begin making the appropriate changes soon.

**Comment by barrettcw** [comment]
Why not :unsatisfiable and :satisfiable

This would be most consistent with the formal methods literature.

**Comment by mykelk** [comment]
@barrettcw I think the confusion would be that we are talking about the input-output property, not a possible input assignment. We just want to prove whether the property holds (i.e. is satisfied), not that there exists an input that satisfies the output constraint (i.e. is satisfiable). Does that make sense?

**Comment by barrettcw** [comment]
Oh wait - you are using :satisfied as a synonym for :holds ?  I think that is even worse.  :)

How about we go back to Guy's suggestion - :holds and :violated.  Using any variation of sat and unsat will cause immense confusion.

**Comment by mykelk** [comment]
Fine with me. @changliuliu and @clazarus , is that okay?

**Comment by clazarus** [comment]
I agree with Clark. 

If I understood correctly, `:SAT/:satisfied` and `:UNSAT/:unsatisfied` would still evoke the meaning they have in the context of boolean satisfiability problems and could potentially lead users to interpret them with the opposite meaning of what they currently have in this package (i.e. the way Reluplex uses the terms). I believe `:holds` and `:violated` do not evoke this context and are unambiguous. 

I will wait for @changliuliu's confirmation before making the pertinent changes.
