### ISSUE TITLE
MaxSens Excessive Memory Usage

### ISSUE THREAD

**Issue by chelseas** [sisl/NeuralVerification.jl#42]
I am trying to run some properties on a network with the following structure:
7,5,10,22, (7 layers, input dim of 5, output dim of 10, largest layer 22 neurons wide)
The layers have the following sizes:
5,14,14,18,18,22,22,10,

Running on a server with 125 GB of RAM, it used 165GB of memory (some swap there too) and ran for 13 hours before I killed it. On a machine with 31GB of ram, I'm running it now and it's currently using 36GB of memory and counting.

**Comment by tclayton0594** [comment]
Hi, I would like to follow up this post. I too have run into issues with running out of memory when using MaxSens. My network is smaller than NNs that you all tested the solver with (3 hidden layers with 30 neurons each). I know in the paper it was mentioned that large input/output dimensions could cause large memory usage, but my input dimension is only 5 as well. 

What were the specs on the computer that you guys were able to get quick results out of MaxSens on large NNs?

**Comment by tomerarnon** [comment]
@tclayton0594, what was the resolution you ran MaxSens with?

**Comment by tclayton0594** [comment]
@tomerarnon I tried resolutions as low as 0.01 and as high as 100

**Comment by tomerarnon** [comment]
We warn if this will happen now #146.
