### ISSUE TITLE
Encode some output constraints as "PolytopeComplement"

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#44]
As per the discussion earlier today, we should create a new type which represents the complement of a polytope. This will allow us to capture more expressive output sets in certain algorithms.

**Comment by tomerarnon** [comment]
Most optimization and reachability algorithms call `tosimplehrep` on the output set, converting a polytope to `C, d` as in `Cx ≤ d`.
 It does not seem correct to do something like `-C, d` to get the complement. For a single halfspace it would work, naturally, but in general it is not correct (right?).

**Comment by schillic** [comment]
A polytope is a conjunction of constraints, ⋀ᵢ cᵢ. The complement is ⋁ᵢ ¬cᵢ, - a disjunction of the complemented constraints, which is typically not a convex set anymore.

**Comment by tomerarnon** [comment]
Having taken another look, the algorithms that _require_ complementary outputs and those that call `tosimplehrep` do not overlap, so for now we may simply have to limit the use `PolyotopeComplements` to work only on the algorithms that really need them. Since the complement of the complement of a PolytopeComlement (say that three times fast..) is convex, we don't need to limit ourselves to complements of halfspaces for those algorithms.

**Comment by tomerarnon** [comment]
`@constraint` requires `<=` or `>=`, i.e. does not allow `<, >` so the encoded complementary constraint is not strict. Does this affect soundness @changliuliu?

**Comment by changliuliu** [comment]
This affects completeness instead of soundness. Essentially, the constraints for the complementary set is more conservative with >= or <= than > or <. We haven't mentioned this point in the paper. But the difference only lies on the boundary the constraint, e.g., where "=" holds.

**Comment by tomerarnon** [comment]
In that case, `NSVerify, MIPVerify, Planet`, and `Reluplex` are affected by this, since ostensibly they should be complete.

**Comment by changliuliu** [comment]
I will add a comment in the paper. Could you please also add a comment to the documentation?

We can say something like: NSVerify, MIPVerify, Planet, and Reluplex are complete w.r.t an ''open'' (instead of ''closed'') output set. Openness of the output set implies that its complement is closed, hence compatible with >= or <= constraints.

**Comment by tomerarnon** [comment]
> We can say something like: NSVerify, MIPVerify, Planet, and Reluplex are complete w.r.t an ''open'' (instead of ''closed'') output set. 

Hmm... In that case, using a `PolytopeComplement` preserves completeness, since the complement is necessarily open. It is actually in the case of `HalfSpace`/`HPolytopes` that we lose completeness

**Comment by changliuliu** [comment]
Yes, this issue is not particular to ```PolytopeComplement```. It happens only because we cannot encode open constraints in ```add_complementary_set_constraints```. For ```HalfSpace```, we also included the boundary in the complement.

**Comment by tomerarnon** [comment]
Hmm... Yes this is definitely worth discussing in the docs.

Since using `PolytopeComplement` actually ensures completeness, while other sets do not, would it be crazy to limit the allowed outputs to be only complements, even if one wanted, e.g. a halfspace, since encoding that directly would not be complete?

**Comment by changliuliu** [comment]
> would it be crazy to limit the allowed outputs to be only complements

That's actually a good idea. It also improves consistency. And we can say that ```PolytopeComplement``` is an open set by definition.

**Comment by tomerarnon** [comment]
I'll add it. 
We noted in #30 that Reluplex should be able to handle general hpolytopes rather than just halfspaces, and PolytopeComplements enables this. Is this true of the other solvers as well (I am creating a table in the docs)

**Comment by changliuliu** [comment]
Yes, the idea of introducing PolytopeComplement to make the output set more general was originated from #30 . Then it also benefits other solvers (NSVerify, MIPVerify, ILP, Planet) that only encode the complement of the output set. Before we introduce PolytopeComplement, they can only take half space constraint since they require the complement of the constraint to be convex. Back then, the complement constraint that we encode is not the complement of a "closed" half space, but the complement of an "open" half space.

**Comment by tomerarnon** [comment]
I added some docs to #52. Would be good if you could review for accuracy/clarity.
