### ISSUE TITLE
Update JuMP

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#45]
We are using an old version of JuMP. The latest version has different functions, variables and syntax so switching over could be a bit of a project.

**Comment by tomerarnon** [comment]
Just took another look. Two major advantages to upgrading:

1) [Variables are queryable from the model by name.](http://www.juliaopt.org/JuMP.jl/v0.19.0/variables/#What-is-a-JuMP-variable?-1) This means we don't necessarily have to carry around `neurons` and `deltas`, etc. everywhere we go. We can access them with e.g. `model[:z]`, which is just grand.

2) [Constraints are deletable](http://www.juliaopt.org/JuMP.jl/v0.19.0/constraints/#Constraint-deletion-1). Instead of rewriting the entire problem in Reluplex with each recursion, we simply `delete` an unsuccessful constraint. 

Downsides, on top of the solver factory thing and the variable renaming, [tons of other breaking changes](https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md). We will pretty much need to comb over every optimization line. That said, it could be well worth the new features (haven't gone over all of them).

**Comment by mykelk** [comment]
Let's do it! It looks like much of the [basic syntax](http://www.juliaopt.org/JuMP.jl/v0.19.0/quickstart/#Quick-Start-Guide-1) is the same.

**Comment by khedher1984** [comment]
Thank you for your help.
The version installed is 0.19.0 however the code is implemented under the version 0.17.0.
I try this command Pkg.add("JuMP",v"0.17.0") but it not passed.
can someone help me ?

**Comment by tomerarnon** [comment]
In Julia 1.0+, you need to do something like this from the package manager:

```
(v1.0) pkg> add JuMP@0.18.5
```
 [See this discourse thread](https://discourse.julialang.org/t/how-to-pin-a-package-to-previous-version-on-julia-1-0/13661/6). Hope that resolves it.
Note that the version you want is not 0.17.0, but 0.18.5, which is the one the one listed in the Manifest file.

**Comment by khedher1984** [comment]
Tank you very munch. I removed JuMP and installed it using the command  add JuMP@0.18.5
It works now !
