### ISSUE TITLE
Hyperrectangle linear_transformation

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#49]
@changliuliu 
I am updating certain functions, `linear_transformation` among them. See:
https://github.com/sisl/NeuralVerification.jl/blob/84001f4cda486358ad7b0f92068f14c78dcd0224/src/utils/util.jl#L295

I am wondering if this function is technically incorrect. In general, a transformation of a hyperrectangle is not necessarily a hyperrectangle; what it's here doing is something like an over-approximation of the transformed set (but I wasn't sure if that was exactly it). If this is definitely the desired behavior, then that's fine, just making sure.

**Comment by changliuliu** [comment]
It is an over-approximation. We compute the bounds for nodes after the linear map and ignore the dependency among these nodes. This function is called when we try to transfer node-wise bounds on the last layer to before activation node-wise bounds on the current layer.

**Comment by changliuliu** [comment]
Maybe we can give it another name to avoid confusion.

**Comment by tomerarnon** [comment]
Ok, in that case I will rename it. Is it the same sort of overapproximation we would get with e.g. `overapproximate(linear_map(L, H))`. I.e. by first computing the linear map and then taking the superscribing hyperrectangle?

**Comment by changliuliu** [comment]
Yes, they are the same. But I think overapproximate(linear_map(L, H)) is less efficient.

**Comment by tomerarnon** [comment]
@mforets awesome!

@changliuliu I'll update to overapproximate(LinearMap(L, H)) which should now be the same as that function
