### ISSUE TITLE
Certify unknown vs violated

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#55]
`Certify` currently cannot return `:violated`
```julia 
function interpret_result(solver::Certify, status, o)
    if value(o) <= 0
        return BasicResult(:holds)
    else
        return BasicResult(:unknown)
    end
end
```

Since `Certify` is not complete anyway, we should simply change `:unknown` to `:violated`, unless there is a truly `:violated` case to add as well.

**Comment by changliuliu** [comment]
Let's return ```:violated``` for ```:unknown``` then.
