### ISSUE TITLE
NSVerify bug

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#64]
@clazarus reported an incorrect :holds with NSVerify (or some similar incorrect result).

**Comment by tclayton0594** [comment]
Hi, is this still a concern for NSVerify and potentially other "complete" solvers? I have recently used your solvers on a NN with 3 hidden layers and 30 neurons per layer and got helpful results. However, I noticed that some solvers listed as "complete" gave incorrect answers. In particular, Reluval and Reluplex gave incorrect results. Reluval gave a counter example violation, which happened to be the exact midpoint of the input space and Reluplex gave an incorrect :holds. NSVerify did in fact return a valid counter example however. Any thoughts on what may be going on?

**Comment by tomerarnon** [comment]
Hi @tclayton0594, I haven't replicated that particular erroneous result and maybe @clazarus can say more at the moment. I'll look into it soon to figure out the cause of the issue (I suspect it's numerical instability, but I didn't personally see the problem).

**Comment by tclayton0594** [comment]
Ok I thought ReluVal was complete due to the chart in your paper, but it was actually the opposite. ReluVal gave an invalid counter example. I will open up another discussion with as much info and screenshots as I can, but I do work for General Motors and the NN we are trying to verify is for future production.

**Comment by mykelk** [comment]
@changliuliu and @kjulian3 are likely to have some comments on this.

**Comment by changliuliu** [comment]
If we allow ReluVal to run until convergence (set max_iter to infinity), then it is complete. In the paper, we classify it to be complete under the assumption that 1) there is no constraint on the number of iterations it can take and 2) ReluVal should always terminate in finite steps (this is claimed by the ReluVal authors).

**Comment by tomerarnon** [comment]
Should have been resolved in #120.
