### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#66]
Roadblocks:
 - CDDLib fails to compile
    - not in the CDDLib issues. Fix unknown.
 - PicoSAT can't compile
    - can disable Planet to fix.
    - can remove PicoSAT in favor of something else.
    - can figure out how to get PicoSAT to compile on windows an send PR to those folks (it's in their issues as well).

**Comment by MaximeBouton** [comment]
It should be fixed once this is merged: jakebolewski/PicoSAT.jl#14 and a new version of PicoSAT.jl is released. 

[CDDLib.jl](https://github.com/JuliaPolyhedra/CDDLib.jl) seems to be using BinaryBuilder and work cross-platform already.

**Comment by tomerarnon** [comment]
Thanks @MaximeBouton! This is great, and I'll check out CDDLib.jl again as well. A lot has changed since this issue was opened, which is great to see.

**Comment by mforets** [comment]
> This is great, and I'll check out CDDLib.jl again as well

CDDLib devs have fixed Windows build and added AppVeyor for CI in Windows, see the latest CDDLib [release v0.5.3](https://github.com/JuliaPolyhedra/CDDLib.jl/releases/tag/v0.5.3).
