### ISSUE TITLE
Security warning due to examples env requirements (TensorFlow)

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#69]
@clazarus is there any way to get around this? It's due to TensorFlow (and maybe other requirements) being a dependency of the examples.

**Comment by rejuvyesh** [comment]
You can likely just remove the versions in https://github.com/sisl/NeuralVerification.jl/blob/master/examples/cars_workshop/requirements.txt

**Comment by tomerarnon** [comment]
Thanks @rejuvyesh! Just removing the version should take care of it?

**Comment by rejuvyesh** [comment]
Yeah. Removing version requirements means that you allow for the latest versions that have the latest security features. For most things latest versions should not be an issue. But you can keep version requirements for individual packages that you need specific versions of.
