### ISSUE TITLE
Hyperrectangle not defined

### ISSUE THREAD

**Issue by AvrahamRaviv** [sisl/NeuralVerification.jl#75]
Hi
I tried to run your example, but tackled by this error:
julia> input_set  = Hyperrectangle(low = [-1.0], high = [1.0])
ERROR: UndefVarError: Hyperrectangle not defined
Stacktrace:
 [1] top-level scope at REPL[11]:1

all the earlier steps were good.

Does anyone know this issue?
thanks

**Comment by tomerarnon** [comment]
Try: `using LazySets`

**Comment by AvrahamRaviv** [comment]
thanks!
seems it's ok now.
