### ISSUE TITLE
Constraints on Certify

### ISSUE THREAD

**Issue by tomerarnon** [sisl/NeuralVerification.jl#80]
(Note: not relevant for the paper!)

https://github.com/sisl/NeuralVerification.jl/blob/95582fc975512b39ead9a8df4a8a229f3bf8a4e1/src/optimization/certify.jl#L33-L51

@changliuliu, I want to be sure the constraints imposed on `Certify` are accurate. In the docstring, we say: "Network: one hidden layer, any activation that is differentiable almost everywhere whose derivative is bound by 0 and 1" but in the code, it looks like we also assume the output is a scalar. This is based on the `1` used to index in a couple of places and looking at only `first(o)` in the result (if it wasn't length 1, we should care about all entries I think...). Anyway let me know if this is true and we can add in a simple `assert` statement to handle it.

**Comment by changliuliu** [comment]
It does not assume scalar output layer.

The ```output``` in the code is actually the cost value c*y - d. See line 43. It essentially adds another linear layer after the original network and maps the output of the network to a scalar value.

**Comment by tomerarnon** [comment]
>  c*y - d

Ah I see. Since it's limited to halfspace output constraints, _this_ is where it becomes a scalar. Ok, excellent! I was doing a pass through algorithms that developed an error after a package update and caught that spot that looked suspicious. Nothing to see here apparently!
