### ISSUE TITLE
Pkg dependencies problem

### ISSUE THREAD

**Issue by Student2Pro** [sisl/NeuralVerification.jl#86]
Thanks to @tomerarnon @mforets my code pass test on my laptop but print this warning:
![图片](https://user-images.githubusercontent.com/59324381/74580532-2f1e3980-4fe0-11ea-94a2-051ce34eafcc.png)
what does that mean and what should I do to fix it?
![图片](https://user-images.githubusercontent.com/59324381/74580758-950bc080-4fe2-11ea-9cc0-67c887294c02.png)

**Comment by mforets** [comment]
The source of the warning (you can ignore it while you develop..) is in the `Project.toml` file,

> Package NVtest does not have LazySets in its dependencies

the file https://github.com/Student2Pro/NVtest.jl/blob/master/Project.toml should include the dependencies.

Regarding package development in general, you may find useful to [read the documentation](https://julialang.github.io/Pkg.jl/v1/toml-files/) or watch some tutorials (eg. [this one](https://www.youtube.com/watch?v=QVmU29rCjaA)).

**Comment by Student2Pro** [comment]
This is awkward. It is my mistake. I thought ‘using LazySets' means dependencies between my project and LazySets. I was too reckless to start without fully understanding of Julia Pkg developement. Thanks for the documentation and your patience.
