### ISSUE TITLE
function partition in maxSens.jl need to be fixed

### ISSUE THREAD

**Issue by Student2Pro** [sisl/NeuralVerification.jl#94]
This is the current implementation:
it would err when partition hyperrectangles in space more than 2 dim, Cuboids for example.
```julia
function partition(input::Hyperrectangle, delta::Float64)
    n_dim = dim(input)
    lower, upper = low(input), high(input)
    radius = fill(delta/2, n_dim)

    hyperrectangle_list = [1; ceil.(Int, (upper - lower)/delta)]
    n_hyperrectangle = prod(max.(hyperrectangle_list, 1))

    hyperrectangles = Vector{Hyperrectangle}(undef, n_hyperrectangle)
    for k in 1:n_hyperrectangle
        n = k
        center = Vector{Float64}(undef, n_dim)
        for i in n_dim:-1:1
            id = div(n-1, hyperrectangle_list[i])
            n = mod(n-1, hyperrectangle_list[i])+1
            lower_cell = lower[i] + min(delta, input.radius[i]*2) * id
            radius[i] = min(delta, upper[i] - lower_cell) * 0.5
            center[i] = lower_cell + radius[i];
        end
        hyperrectangles[k] = Hyperrectangle(center[:], radius[:])
    end
    return hyperrectangles
end
```
I think these two sentences dosen't make sense:
```julia
id = div(n-1, hyperrectangle_list[i])
n = mod(n-1, hyperrectangle_list[i])+1
```
And it could be fixed like this: (probably not the best solution)
```julia
function partition(input::Hyperrectangle, delta::Float64)
    n_dim = dim(input)
    lower, upper = low(input), high(input)
    radius = fill(delta/2, n_dim)

    hyperrectangle_list = ceil.(Int, (upper - lower)/delta)

    part_list = zeros(Int64, n_dim)
    part_list[1] = 1
    for j in 2:n_dim
        part_list[j] = part_list[j-1] * max(hyperrectangle_list[j-1], 1)
    end

    n_hyperrectangle = part_list[n_dim] * max(hyperrectangle_list[n_dim], 1)

    hyperrectangles = Vector{Hyperrectangle}(undef, n_hyperrectangle)
    for k in 1:n_hyperrectangle
        n = k - 1
        center = Vector{Float64}(undef, n_dim)
        for i in n_dim:-1:1
            id = div(n, part_list[i])
            n = mod(n, part_list[i])
            lower_cell = lower[i] + min(delta, input.radius[i]*2) * id
            radius[i] = min(delta, upper[i] - lower_cell) * 0.5
            center[i] = lower_cell + radius[i];
        end
        hyperrectangles[k] = Hyperrectangle(center[:], radius[:])
    end
    return hyperrectangles
end
```
Another issue is that it could be better using BigInt than Int64 to store the number of hyperrectangles because the test on mnist1 in runtime1.jl generate more than 4^700 hyperectangles.

**Comment by tomerarnon** [comment]
Thanks for pointing this out @Student2Pro! Your fix does indeed prevent an occasional negative radius from appearing (and maybe other nasty stuff as well 😬).

I've never been quite satisfied with that function, and this made me look deeper into it. Essentially, we are assigning each "cell" in the input its own HR (all of equal size). Any that extend beyond the original boundary are truncated. This can be done more cleanly by imagining the original HR as an N-d array, and traversing that array using its cartesian indices to determine which cell we're at.
It would be cleanest to use `CartesianIndices`, but doing so wouldn't be type stable in this context (and ended up being much slower), so I implemented a workaround below:

```julia
# Utility to avoid using CartesianIndices
function to_cartesian_ind!(I::Integer, limits, output::AbstractVector)
    for i in firstindex(output):lastindex(output)
        I, r = fldmod1(I, limits[i])
        output[i] = r
    end
    output
end

function partition(H, Δ)
    lower, upper = low(H), high(H)

    # The number of sub-hyperrectangles that fit in each dimension, rounding up
    n_hypers_per_dim = max.(ceil.(Int, (upper-lower) / Δ), 1)

    hypers = Vector{typeof(H)}(undef, prod(n_hypers_per_dim))

    # preallocate work arrays
    local_lower, local_upper, CI = similar(lower), similar(lower), similar(lower)
    for i in 1:length(hypers)
        to_cartesian_ind!(i, n_hypers_per_dim, CI)

        @. local_lower = lower + Δ * (CI - 1)
        @. local_upper = min(local_lower + Δ, upper)

        hypers[i] = Hyperrectangle(low = local_lower, high = local_upper)            
    end
    hypers
end
```

Let me know your thoughts. Is this clearer to someone approaching the code with fresh eyes (and equally correct as yours)?

**Comment by Student2Pro** [comment]
@tomerarnon The new code doesn't change the way to compute CartesianIndices, right? In my opinion, the way you compute CartesianIndices is correct in 2 dim, but in higher dim it is not. You can try to partiton a cube with delta equal to it's radius, it should return 8 little cubes, otherwise the function would be wrong.

**Comment by tomerarnon** [comment]
I think the method works with arbitrary dimensionality:

```julia
# all the definitions:
function to_cartesian_ind!(I::Integer, limits, output::AbstractVector)
    for i in firstindex(output):lastindex(output)
        I, r = fldmod1(I, limits[i])
        output[i] = r
    end
    output
end
to_cartesian_ind(LI::Integer, limits::AbstractVector{<:Integer}) = 
    to_cartesian_ind!(LI, limits, similar(limits))
to_cartesian_ind(LI::Integer, limits::NTuple{N, I}) where {N, I<:Integer} = 
    to_cartesian_ind!(LI, limits, Vector{I}(undef, N))



# random multi dimensional test:
julia> LI = LinearIndices((5,3,6,5,9));

julia> collect.(Tuple.(CartesianIndices(LI))) == to_cartesian_ind.(LI, [size(LI)])
true
```

**Comment by Student2Pro** [comment]
> 
> 
> >You say you saw such a number produced in the tests?

https://github.com/sisl/NeuralVerification.jl/blob/ac4eea2d30db3590ee5f03b471682706b6aeb491/test/runtime1.jl#L72

From this line to

https://github.com/sisl/NeuralVerification.jl/blob/ac4eea2d30db3590ee5f03b471682706b6aeb491/test/runtime1.jl#L205

It should be, but it's beyond my laptop so all I got is 0. As for the new code, I must misunderstand something, you're right.

**Comment by tomerarnon** [comment]
Forwarding the question on runtime1.jl to @clazarus
