### ISSUE TITLE
NV.jl overwritten JuMP

### ISSUE THREAD

**Issue by AviadSlo** [sisl/NeuralVerification.jl#98]
I upgrade my JuMP.jl and than got the following warning:

julia> using NeuralVerification

> WARNING: Method definition (::Type{JuMP.Model})(Any) in module JuMP at C:\Users\user\.julia\packages\JuMP\CZ8vV\src\JuMP.jl:233 overwritten in 
module NeuralVerification at C:\Users\user\.julia\packages\NeuralVerification\fHqlR\src\NeuralVerification.jl:22.
  ** incremental compilation may be fatally broken for this module **

well, it's still just a warning, but later I got the following error:
>┌ Warning: `with_optimizer` is deprecated. Adapt the following example to update your code:
│ `with_optimizer(Ipopt.Optimizer)` becomes `Ipopt.Optimizer`.
│   caller = approx_bound(::Network, ::Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}, ::Type{T} where T, ::Symbol) at bab.jl:112   
└ @ NeuralVerification C:\Users\user\.julia\packages\NeuralVerification\fHqlR\src\satisfiability\bab.jl:112
ERROR: type DataType has no field optimizer 

what can I do to solve this issue? Thanks

**Comment by tomerarnon** [comment]
This issue will be resolved soon. In the short term, you can pin your JuMP to an 0.20 version (0.20.1 is the one in the Manifest) which should work for now.

**Comment by tomerarnon** [comment]
closed by #45
